# Generated by Django 3.1.1 on 2020-09-29 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_property', models.CharField(max_length=100)),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.profile')),
            ],
        ),
    ]
