# Generated by Django 3.1.1 on 2020-09-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='Type',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='no_of_property',
        ),
    ]
