# Generated by Django 3.0.2 on 2020-09-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_remove_user_user_type'),
        ('BookingManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingManagement',
            new_name='Booking',
        ),
    ]
