# Generated by Django 3.0.2 on 2020-09-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyManagement', '0002_remove_property_property_id'),
        ('UserManagement', '0007_remove_user_user_type'),
        ('PaymentManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='PropertyManagement.Property')),
                ('travel', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Traveller')),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentManagement',
        ),
    ]
