# Generated by Django 3.1.1 on 2020-09-29 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=200)),
                ('property_location', models.CharField(max_length=200)),
                ('No_of_rooms', models.IntegerField(blank=True, null=True)),
                ('property_description', models.CharField(max_length=200)),
                ('property_pricing', models.FloatField(blank=True, null=True)),
                ('legal_documents', models.ImageField(blank=True, default='images/property/land-documents.jpg', null=True, upload_to='images/property')),
                ('Property_picture', models.ImageField(blank=True, default='images/property/house.jpg', null=True, upload_to='images/property')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.owner')),
            ],
        ),
    ]
