# Generated by Django 3.1.1 on 2020-09-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_ID', models.IntegerField(blank=True, null=True)),
                ('property_name', models.CharField(max_length=200)),
                ('property_location', models.CharField(max_length=200)),
                ('property_details', models.CharField(max_length=200)),
                ('property_pricing', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
