# Generated by Django 3.1.2 on 2020-10-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyManagement', '0002_auto_20200929_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='No_of_rooms',
            new_name='no_of_rooms',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='Property_picture',
            new_name='property_picture',
        ),
    ]
