# Generated by Django 3.1.2 on 2020-10-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyManagement', '0003_auto_20201005_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='legal_documents',
            field=models.ImageField(blank=True, default='images/property/land-documents.jpg', upload_to='images/property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_picture',
            field=models.ImageField(blank=True, default='images/property/house.jpg', upload_to='images/property'),
        ),
    ]
