# Generated by Django 3.1.1 on 2020-09-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagement', '0006_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveller', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.traveller')),
            ],
        ),
    ]
