# Generated by Django 3.1.1 on 2020-09-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='No_of_Guests',
            field=models.IntegerField(max_length=100),
        ),
    ]
