# Generated by Django 3.1.1 on 2020-09-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_auto_20200929_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='No_of_Guests',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
