# Generated by Django 3.1.1 on 2020-09-30 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Traveller', '0002_auto_20200930_0053'),
        ('PropertyManagement', '0002_auto_20200929_2256'),
        ('Booking', '0004_remove_booking_traveller_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Property_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PropertyManagement.property'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Traveller_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Traveller.traveller'),
        ),
    ]
