# Generated by Django 3.1.1 on 2020-09-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/pro_pics/default.jpg', null=True, upload_to='images/pro_pic'),
        ),
    ]
