# Generated by Django 3.1.1 on 2020-09-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.IntegerField(blank=True, default='', null=True)),
                ('street_address', models.CharField(max_length=200)),
                ('postal_address', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='use_type',
            new_name='user_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
