# Generated by Django 3.1.1 on 2020-09-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_auto_20200921_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nid_id',
            new_name='NID_ID',
        ),
    ]
