# Generated by Django 3.1.1 on 2020-09-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_auto_20200929_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Address',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Full_name',
            new_name='Full_Name',
        ),
        migrations.AddField(
            model_name='profile',
            name='State',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Street_Address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
