# Generated by Django 3.1.1 on 2020-09-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_auto_20200921_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
