# Generated by Django 3.0.2 on 2020-09-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
