# Generated by Django 3.1.1 on 2020-09-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Traveller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveller',
            old_name='User_Type',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='traveller',
            name='travelling_area',
        ),
    ]
